FROM amazoncorretto:17

# Create a directory for the application
RUN mkdir /app

# Set the working directory to /app
WORKDIR /app

# Copy the JAR file from the build directory to the container
COPY build/libs/*.jar /app/app.jar

# Expose port 8081
EXPOSE 8081

# Set the entry point to run the JAR file
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
